### PR TITLE
Fix "page.extra.toc" -> "config.extra.toc"

### PR DESCRIPTION
**Pull request by jessun**

### CODE REVIEW

**Comment by VersBinarii** [comment]
What does this change supposed to do?

**Comment by jessun** [comment]
> What does this change supposed to do?

This change fix content toc due to README: https://github.com/VersBinarii/hermit_zola#table-of-content.

**Comment by VersBinarii** [comment]
This part in README describes that config that needs to be put to the Front matter. Not to the config.toml.
Thats why you have `page.extra.toc` - to acces it from the page front matter extra section.

**Comment by jessun** [comment]
As my test, only `config.extra.toc` works. And it will show a `toc button icon` in a page.html.
Please confirm it.

**Comment by VersBinarii** [comment]
Well thats becuse you probably placed it in the config.extra section in your setup. But this is not how it was intended to use it in this template.
The idea here is that you can control the TOC per page - hence the config is placed in grey matter of your markdown.
Grey matter is the initial +++ +++ section of your post  markdown file.
I just updated the typography.md example and README.

**Comment by jessun** [comment]
Ohhh..... I finally understand your intention. Thank you for the explanation.

**Pull request closed without merging**
